### ISSUE TITLE
English translation?

### ISSUE THREAD

**Issue by jawz101** [ohdarling/COVID-19-Charts#1]
I was looking for beautiful representations of the outbreak and I was wondering if it would be much effort to offer an English translation option on your site?  Even if the translation was initially created with Google Translate I could submit any translation fixes if you wanted.

**Comment by ohdarling** [comment]
I wil setup the UI translation as soon as possible.

**Comment by jawz101** [comment]
Awesome.  I love seeing these types of analyses.  And if you have any geographic information I've started playing with making choropleths in an open source app called QGIS.

**Comment by ohdarling** [comment]
English UI was added.

The data source does not have geo information, the map was using name to map area in the map.

Any other question you can start another issue :)
